import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { Geist, Geist_Mono } from "next/font/google";
const CartDrawer = dynamic(() => import('@/components/cart/CartDrawer'));
import "./globals.css";
import AuthInitializer from "@/components/admin/auth/AuthInitializer";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ecommerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthInitializer />
<Toaster
  position="top-right"
  toastOptions={{
    style: {
      backgroundColor: "#1a1f1a",
      color: "#c7f9cc",
      border: "1px solid #37b24d",
      borderRadius: "8px",
    },
    success: {
      style: {
        backgroundColor: "#0f5132",
        color: "#d1e7dd",
      },
    },
    error: {
      style: {
        backgroundColor: "#842029",
        color: "#f8d7da",
      },
    },
  }}
/>        {children} 
        <CartDrawer />
      </body>
    </html>
  );
}
